// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: symmetric.proto

package symmetric

import (
	common "github.com/basarardabaykal/cipherconverter-microservice/internal/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CaesarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          []byte                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Shift         int32                  `protobuf:"varint,2,opt,name=shift,proto3" json:"shift,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaesarRequest) Reset() {
	*x = CaesarRequest{}
	mi := &file_symmetric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaesarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaesarRequest) ProtoMessage() {}

func (x *CaesarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_symmetric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaesarRequest.ProtoReflect.Descriptor instead.
func (*CaesarRequest) Descriptor() ([]byte, []int) {
	return file_symmetric_proto_rawDescGZIP(), []int{0}
}

func (x *CaesarRequest) GetText() []byte {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *CaesarRequest) GetShift() int32 {
	if x != nil {
		return x.Shift
	}
	return 0
}

type ColumnarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          []byte                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Columns       int32                  `protobuf:"varint,2,opt,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnarRequest) Reset() {
	*x = ColumnarRequest{}
	mi := &file_symmetric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnarRequest) ProtoMessage() {}

func (x *ColumnarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_symmetric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnarRequest.ProtoReflect.Descriptor instead.
func (*ColumnarRequest) Descriptor() ([]byte, []int) {
	return file_symmetric_proto_rawDescGZIP(), []int{1}
}

func (x *ColumnarRequest) GetText() []byte {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *ColumnarRequest) GetColumns() int32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

type OTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          []byte                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OTPRequest) Reset() {
	*x = OTPRequest{}
	mi := &file_symmetric_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OTPRequest) ProtoMessage() {}

func (x *OTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_symmetric_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OTPRequest.ProtoReflect.Descriptor instead.
func (*OTPRequest) Descriptor() ([]byte, []int) {
	return file_symmetric_proto_rawDescGZIP(), []int{2}
}

func (x *OTPRequest) GetText() []byte {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *OTPRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_symmetric_proto protoreflect.FileDescriptor

const file_symmetric_proto_rawDesc = "" +
	"\n" +
	"\x0fsymmetric.proto\x12\tsymmetric\x1a\fcommon.proto\"9\n" +
	"\rCaesarRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\fR\x04text\x12\x14\n" +
	"\x05shift\x18\x02 \x01(\x05R\x05shift\"?\n" +
	"\x0fColumnarRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\fR\x04text\x12\x18\n" +
	"\acolumns\x18\x02 \x01(\x05R\acolumns\"2\n" +
	"\n" +
	"OTPRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\fR\x04text\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key2\x9d\x03\n" +
	"\rCipherService\x12A\n" +
	"\rEncryptCaesar\x12\x18.symmetric.CaesarRequest\x1a\x16.common.CipherResponse\x12A\n" +
	"\rDecryptCaesar\x12\x18.symmetric.CaesarRequest\x1a\x16.common.CipherResponse\x12E\n" +
	"\x0fEncryptColumnar\x12\x1a.symmetric.ColumnarRequest\x1a\x16.common.CipherResponse\x12E\n" +
	"\x0fDecryptColumnar\x12\x1a.symmetric.ColumnarRequest\x1a\x16.common.CipherResponse\x12;\n" +
	"\n" +
	"EncryptOTP\x12\x15.symmetric.OTPRequest\x1a\x16.common.CipherResponse\x12;\n" +
	"\n" +
	"DecryptOTP\x12\x15.symmetric.OTPRequest\x1a\x16.common.CipherResponseBOZMgithub.com/basarardabaykal/cipherconverter-microservice/internal/pb/symmetricb\x06proto3"

var (
	file_symmetric_proto_rawDescOnce sync.Once
	file_symmetric_proto_rawDescData []byte
)

func file_symmetric_proto_rawDescGZIP() []byte {
	file_symmetric_proto_rawDescOnce.Do(func() {
		file_symmetric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_symmetric_proto_rawDesc), len(file_symmetric_proto_rawDesc)))
	})
	return file_symmetric_proto_rawDescData
}

var file_symmetric_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_symmetric_proto_goTypes = []any{
	(*CaesarRequest)(nil),         // 0: symmetric.CaesarRequest
	(*ColumnarRequest)(nil),       // 1: symmetric.ColumnarRequest
	(*OTPRequest)(nil),            // 2: symmetric.OTPRequest
	(*common.CipherResponse)(nil), // 3: common.CipherResponse
}
var file_symmetric_proto_depIdxs = []int32{
	0, // 0: symmetric.CipherService.EncryptCaesar:input_type -> symmetric.CaesarRequest
	0, // 1: symmetric.CipherService.DecryptCaesar:input_type -> symmetric.CaesarRequest
	1, // 2: symmetric.CipherService.EncryptColumnar:input_type -> symmetric.ColumnarRequest
	1, // 3: symmetric.CipherService.DecryptColumnar:input_type -> symmetric.ColumnarRequest
	2, // 4: symmetric.CipherService.EncryptOTP:input_type -> symmetric.OTPRequest
	2, // 5: symmetric.CipherService.DecryptOTP:input_type -> symmetric.OTPRequest
	3, // 6: symmetric.CipherService.EncryptCaesar:output_type -> common.CipherResponse
	3, // 7: symmetric.CipherService.DecryptCaesar:output_type -> common.CipherResponse
	3, // 8: symmetric.CipherService.EncryptColumnar:output_type -> common.CipherResponse
	3, // 9: symmetric.CipherService.DecryptColumnar:output_type -> common.CipherResponse
	3, // 10: symmetric.CipherService.EncryptOTP:output_type -> common.CipherResponse
	3, // 11: symmetric.CipherService.DecryptOTP:output_type -> common.CipherResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_symmetric_proto_init() }
func file_symmetric_proto_init() {
	if File_symmetric_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_symmetric_proto_rawDesc), len(file_symmetric_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_symmetric_proto_goTypes,
		DependencyIndexes: file_symmetric_proto_depIdxs,
		MessageInfos:      file_symmetric_proto_msgTypes,
	}.Build()
	File_symmetric_proto = out.File
	file_symmetric_proto_goTypes = nil
	file_symmetric_proto_depIdxs = nil
}
