// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: symmetric.proto

package symmetric

import (
	context "context"
	common "github.com/basarardabaykal/cipherconverter-microservice/internal/pb/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CipherService_EncryptCaesar_FullMethodName   = "/symmetric.CipherService/EncryptCaesar"
	CipherService_DecryptCaesar_FullMethodName   = "/symmetric.CipherService/DecryptCaesar"
	CipherService_EncryptColumnar_FullMethodName = "/symmetric.CipherService/EncryptColumnar"
	CipherService_DecryptColumnar_FullMethodName = "/symmetric.CipherService/DecryptColumnar"
	CipherService_EncryptOTP_FullMethodName      = "/symmetric.CipherService/EncryptOTP"
	CipherService_DecryptOTP_FullMethodName      = "/symmetric.CipherService/DecryptOTP"
)

// CipherServiceClient is the client API for CipherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CipherServiceClient interface {
	EncryptCaesar(ctx context.Context, in *CaesarRequest, opts ...grpc.CallOption) (*common.CipherResponse, error)
	DecryptCaesar(ctx context.Context, in *CaesarRequest, opts ...grpc.CallOption) (*common.CipherResponse, error)
	EncryptColumnar(ctx context.Context, in *ColumnarRequest, opts ...grpc.CallOption) (*common.CipherResponse, error)
	DecryptColumnar(ctx context.Context, in *ColumnarRequest, opts ...grpc.CallOption) (*common.CipherResponse, error)
	EncryptOTP(ctx context.Context, in *OTPRequest, opts ...grpc.CallOption) (*common.CipherResponse, error)
	DecryptOTP(ctx context.Context, in *OTPRequest, opts ...grpc.CallOption) (*common.CipherResponse, error)
}

type cipherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCipherServiceClient(cc grpc.ClientConnInterface) CipherServiceClient {
	return &cipherServiceClient{cc}
}

func (c *cipherServiceClient) EncryptCaesar(ctx context.Context, in *CaesarRequest, opts ...grpc.CallOption) (*common.CipherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CipherResponse)
	err := c.cc.Invoke(ctx, CipherService_EncryptCaesar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cipherServiceClient) DecryptCaesar(ctx context.Context, in *CaesarRequest, opts ...grpc.CallOption) (*common.CipherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CipherResponse)
	err := c.cc.Invoke(ctx, CipherService_DecryptCaesar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cipherServiceClient) EncryptColumnar(ctx context.Context, in *ColumnarRequest, opts ...grpc.CallOption) (*common.CipherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CipherResponse)
	err := c.cc.Invoke(ctx, CipherService_EncryptColumnar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cipherServiceClient) DecryptColumnar(ctx context.Context, in *ColumnarRequest, opts ...grpc.CallOption) (*common.CipherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CipherResponse)
	err := c.cc.Invoke(ctx, CipherService_DecryptColumnar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cipherServiceClient) EncryptOTP(ctx context.Context, in *OTPRequest, opts ...grpc.CallOption) (*common.CipherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CipherResponse)
	err := c.cc.Invoke(ctx, CipherService_EncryptOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cipherServiceClient) DecryptOTP(ctx context.Context, in *OTPRequest, opts ...grpc.CallOption) (*common.CipherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CipherResponse)
	err := c.cc.Invoke(ctx, CipherService_DecryptOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CipherServiceServer is the server API for CipherService service.
// All implementations must embed UnimplementedCipherServiceServer
// for forward compatibility.
type CipherServiceServer interface {
	EncryptCaesar(context.Context, *CaesarRequest) (*common.CipherResponse, error)
	DecryptCaesar(context.Context, *CaesarRequest) (*common.CipherResponse, error)
	EncryptColumnar(context.Context, *ColumnarRequest) (*common.CipherResponse, error)
	DecryptColumnar(context.Context, *ColumnarRequest) (*common.CipherResponse, error)
	EncryptOTP(context.Context, *OTPRequest) (*common.CipherResponse, error)
	DecryptOTP(context.Context, *OTPRequest) (*common.CipherResponse, error)
	mustEmbedUnimplementedCipherServiceServer()
}

// UnimplementedCipherServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCipherServiceServer struct{}

func (UnimplementedCipherServiceServer) EncryptCaesar(context.Context, *CaesarRequest) (*common.CipherResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EncryptCaesar not implemented")
}
func (UnimplementedCipherServiceServer) DecryptCaesar(context.Context, *CaesarRequest) (*common.CipherResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecryptCaesar not implemented")
}
func (UnimplementedCipherServiceServer) EncryptColumnar(context.Context, *ColumnarRequest) (*common.CipherResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EncryptColumnar not implemented")
}
func (UnimplementedCipherServiceServer) DecryptColumnar(context.Context, *ColumnarRequest) (*common.CipherResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecryptColumnar not implemented")
}
func (UnimplementedCipherServiceServer) EncryptOTP(context.Context, *OTPRequest) (*common.CipherResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EncryptOTP not implemented")
}
func (UnimplementedCipherServiceServer) DecryptOTP(context.Context, *OTPRequest) (*common.CipherResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecryptOTP not implemented")
}
func (UnimplementedCipherServiceServer) mustEmbedUnimplementedCipherServiceServer() {}
func (UnimplementedCipherServiceServer) testEmbeddedByValue()                       {}

// UnsafeCipherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CipherServiceServer will
// result in compilation errors.
type UnsafeCipherServiceServer interface {
	mustEmbedUnimplementedCipherServiceServer()
}

func RegisterCipherServiceServer(s grpc.ServiceRegistrar, srv CipherServiceServer) {
	// If the following call panics, it indicates UnimplementedCipherServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CipherService_ServiceDesc, srv)
}

func _CipherService_EncryptCaesar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaesarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CipherServiceServer).EncryptCaesar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CipherService_EncryptCaesar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CipherServiceServer).EncryptCaesar(ctx, req.(*CaesarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CipherService_DecryptCaesar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaesarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CipherServiceServer).DecryptCaesar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CipherService_DecryptCaesar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CipherServiceServer).DecryptCaesar(ctx, req.(*CaesarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CipherService_EncryptColumnar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ColumnarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CipherServiceServer).EncryptColumnar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CipherService_EncryptColumnar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CipherServiceServer).EncryptColumnar(ctx, req.(*ColumnarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CipherService_DecryptColumnar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ColumnarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CipherServiceServer).DecryptColumnar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CipherService_DecryptColumnar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CipherServiceServer).DecryptColumnar(ctx, req.(*ColumnarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CipherService_EncryptOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CipherServiceServer).EncryptOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CipherService_EncryptOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CipherServiceServer).EncryptOTP(ctx, req.(*OTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CipherService_DecryptOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CipherServiceServer).DecryptOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CipherService_DecryptOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CipherServiceServer).DecryptOTP(ctx, req.(*OTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CipherService_ServiceDesc is the grpc.ServiceDesc for CipherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CipherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "symmetric.CipherService",
	HandlerType: (*CipherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EncryptCaesar",
			Handler:    _CipherService_EncryptCaesar_Handler,
		},
		{
			MethodName: "DecryptCaesar",
			Handler:    _CipherService_DecryptCaesar_Handler,
		},
		{
			MethodName: "EncryptColumnar",
			Handler:    _CipherService_EncryptColumnar_Handler,
		},
		{
			MethodName: "DecryptColumnar",
			Handler:    _CipherService_DecryptColumnar_Handler,
		},
		{
			MethodName: "EncryptOTP",
			Handler:    _CipherService_EncryptOTP_Handler,
		},
		{
			MethodName: "DecryptOTP",
			Handler:    _CipherService_DecryptOTP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "symmetric.proto",
}
