// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: cipher.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CaesarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          []byte                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Shift         int32                  `protobuf:"varint,2,opt,name=shift,proto3" json:"shift,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaesarRequest) Reset() {
	*x = CaesarRequest{}
	mi := &file_cipher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaesarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaesarRequest) ProtoMessage() {}

func (x *CaesarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cipher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaesarRequest.ProtoReflect.Descriptor instead.
func (*CaesarRequest) Descriptor() ([]byte, []int) {
	return file_cipher_proto_rawDescGZIP(), []int{0}
}

func (x *CaesarRequest) GetText() []byte {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *CaesarRequest) GetShift() int32 {
	if x != nil {
		return x.Shift
	}
	return 0
}

type ColumnarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          []byte                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Columns       int32                  `protobuf:"varint,2,opt,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnarRequest) Reset() {
	*x = ColumnarRequest{}
	mi := &file_cipher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnarRequest) ProtoMessage() {}

func (x *ColumnarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cipher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnarRequest.ProtoReflect.Descriptor instead.
func (*ColumnarRequest) Descriptor() ([]byte, []int) {
	return file_cipher_proto_rawDescGZIP(), []int{1}
}

func (x *ColumnarRequest) GetText() []byte {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *ColumnarRequest) GetColumns() int32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

type CipherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CipherResponse) Reset() {
	*x = CipherResponse{}
	mi := &file_cipher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CipherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CipherResponse) ProtoMessage() {}

func (x *CipherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cipher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CipherResponse.ProtoReflect.Descriptor instead.
func (*CipherResponse) Descriptor() ([]byte, []int) {
	return file_cipher_proto_rawDescGZIP(), []int{2}
}

func (x *CipherResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_cipher_proto protoreflect.FileDescriptor

const file_cipher_proto_rawDesc = "" +
	"\n" +
	"\fcipher.proto\x12\x06cipher\"9\n" +
	"\rCaesarRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\fR\x04text\x12\x14\n" +
	"\x05shift\x18\x02 \x01(\x05R\x05shift\"?\n" +
	"\x0fColumnarRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\fR\x04text\x12\x18\n" +
	"\acolumns\x18\x02 \x01(\x05R\acolumns\"(\n" +
	"\x0eCipherResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result2\x97\x02\n" +
	"\rCipherService\x12>\n" +
	"\rEncryptCaesar\x12\x15.cipher.CaesarRequest\x1a\x16.cipher.CipherResponse\x12>\n" +
	"\rDecryptCaesar\x12\x15.cipher.CaesarRequest\x1a\x16.cipher.CipherResponse\x12B\n" +
	"\x0fEncryptColumnar\x12\x17.cipher.ColumnarRequest\x1a\x16.cipher.CipherResponse\x12B\n" +
	"\x0fDecryptColumnar\x12\x17.cipher.ColumnarRequest\x1a\x16.cipher.CipherResponseBEZCgithub.com/basarardabaykal/cipherconverter-microservice/internal/pbb\x06proto3"

var (
	file_cipher_proto_rawDescOnce sync.Once
	file_cipher_proto_rawDescData []byte
)

func file_cipher_proto_rawDescGZIP() []byte {
	file_cipher_proto_rawDescOnce.Do(func() {
		file_cipher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cipher_proto_rawDesc), len(file_cipher_proto_rawDesc)))
	})
	return file_cipher_proto_rawDescData
}

var file_cipher_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cipher_proto_goTypes = []any{
	(*CaesarRequest)(nil),   // 0: cipher.CaesarRequest
	(*ColumnarRequest)(nil), // 1: cipher.ColumnarRequest
	(*CipherResponse)(nil),  // 2: cipher.CipherResponse
}
var file_cipher_proto_depIdxs = []int32{
	0, // 0: cipher.CipherService.EncryptCaesar:input_type -> cipher.CaesarRequest
	0, // 1: cipher.CipherService.DecryptCaesar:input_type -> cipher.CaesarRequest
	1, // 2: cipher.CipherService.EncryptColumnar:input_type -> cipher.ColumnarRequest
	1, // 3: cipher.CipherService.DecryptColumnar:input_type -> cipher.ColumnarRequest
	2, // 4: cipher.CipherService.EncryptCaesar:output_type -> cipher.CipherResponse
	2, // 5: cipher.CipherService.DecryptCaesar:output_type -> cipher.CipherResponse
	2, // 6: cipher.CipherService.EncryptColumnar:output_type -> cipher.CipherResponse
	2, // 7: cipher.CipherService.DecryptColumnar:output_type -> cipher.CipherResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cipher_proto_init() }
func file_cipher_proto_init() {
	if File_cipher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cipher_proto_rawDesc), len(file_cipher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cipher_proto_goTypes,
		DependencyIndexes: file_cipher_proto_depIdxs,
		MessageInfos:      file_cipher_proto_msgTypes,
	}.Build()
	File_cipher_proto = out.File
	file_cipher_proto_goTypes = nil
	file_cipher_proto_depIdxs = nil
}
